"""All named constants used across OmniRAG. No magic numbers elsewhere (R-34)."""

# --- Entity resolution thresholds (Blueprint 2.3 / 8.1) ---
STAGE1_LEXICAL_THRESHOLD = 0.70
STAGE2_SEMANTIC_THRESHOLD = 0.75
ENTITY_AUTO_MERGE_THRESHOLD = 0.85
ENTITY_REVIEW_QUEUE_LOWER_BOUND = 0.60

# --- Retrieval (Blueprint 8.2) ---
RRF_K = 60
RETRIEVAL_TOP_K_PER_SOURCE = 10
GRAPH_EXPANSION_TOP_N_RESULTS = 5

# --- Confidence scoring (Blueprint 8.5) ---
CONFIDENCE_SOURCE_BASE = 0.4
CONFIDENCE_SOURCE_PER_SOURCE = 0.2
CONFIDENCE_SOURCE_MAX = 1.0
CONFIDENCE_CONTRADICTION_PENALTY_PER = 0.15
CONFIDENCE_CONTRADICTION_PENALTY_MAX = 0.4
CONFIDENCE_VERIFIED_MULTIPLIER = 1.15
CONFIDENCE_UNVERIFIED_MULTIPLIER = 1.0
CONFIDENCE_LOW_THRESHOLD = 0.50
CONFIDENCE_VERY_LOW_THRESHOLD = 0.30

# --- Caching ---
QUERY_CACHE_TTL_SECONDS = 300

# --- Rate limits (requests per minute unless noted) — Blueprint 2.4 ---
RATE_LIMIT_AUTH_GOOGLE = "20/minute"
RATE_LIMIT_AUTH_REFRESH = "30/minute"
RATE_LIMIT_WORKSPACE_STATUS = "60/minute"
RATE_LIMIT_INGEST_WEBHOOK = "500/minute"
RATE_LIMIT_INGEST_FILES = "20/minute"
RATE_LIMIT_INGEST_STATUS = "100/minute"
RATE_LIMIT_QUERY = "30/minute"
RATE_LIMIT_GRAPH_READ = "60/minute"
RATE_LIMIT_GRAPH_NODE = "100/minute"
RATE_LIMIT_GRAPH_DRIFT = "30/minute"
RATE_LIMIT_EXPERTS = "60/minute"
RATE_LIMIT_GAPS = "60/minute"
RATE_LIMIT_DOCUMENTS = "60/minute"
RATE_LIMIT_DOCUMENTS_APPROVE = "20/minute"
RATE_LIMIT_HEALTH = "200/minute"

# --- JWT (Blueprint 2.5) ---
JWT_ACCESS_TOKEN_EXPIRY_MINUTES = 15
JWT_REFRESH_TOKEN_EXPIRY_DAYS = 7

# --- File uploads ---
MAX_UPLOAD_FILE_SIZE_MB = 10
SUPPORTED_UPLOAD_FORMATS = {"pdf", "docx"}

# --- Community verification (Blueprint 2.3) ---
KTD_APPROVALS_REQUIRED = 2
KTD_TOP_CONTRIBUTORS_NOTIFIED = 3

# --- API ---
API_VERSION = "v1"
